/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apisCreateApi } from "../funcs/apisCreateApi.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Apis extends ClientSDK {
  async createApi(
    request: components.V2ApisCreateApiRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2ApisCreateApiResponseBody> {
    return unwrapAsync(apisCreateApi(
      this,
      request,
      options,
    ));
  }
}
