/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { identitiesCreateIdentity } from "../funcs/identitiesCreateIdentity.js";
import { identitiesDeleteIdentity } from "../funcs/identitiesDeleteIdentity.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Identities extends ClientSDK {
  async createIdentity(
    request: components.V2IdentitiesCreateIdentityRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2IdentitiesCreateIdentityResponseBody> {
    return unwrapAsync(identitiesCreateIdentity(
      this,
      request,
      options,
    ));
  }

  async deleteIdentity(
    request: components.V2IdentitiesDeleteIdentityRequestBody,
    options?: RequestOptions,
  ): Promise<components.V2IdentitiesDeleteIdentityResponseBody> {
    return unwrapAsync(identitiesDeleteIdentity(
      this,
      request,
      options,
    ));
  }
}
