workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Unkey API:
        inputs:
            - location: ../unkey/go/apps/api/openapi/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/unkey/unkey/unkey-api
targets:
    unkey:
        target: typescript
        source: Unkey API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/unkey/unkey/unkey-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
