/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RatelimitDeleteOverrideResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  v2RatelimitDeleteOverrideResponseBody?:
    | components.V2RatelimitDeleteOverrideResponseBody
    | undefined;
};

/** @internal */
export const RatelimitDeleteOverrideResponse$inboundSchema: z.ZodType<
  RatelimitDeleteOverrideResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  V2RatelimitDeleteOverrideResponseBody: components
    .V2RatelimitDeleteOverrideResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "V2RatelimitDeleteOverrideResponseBody":
      "v2RatelimitDeleteOverrideResponseBody",
  });
});

/** @internal */
export type RatelimitDeleteOverrideResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  V2RatelimitDeleteOverrideResponseBody?:
    | components.V2RatelimitDeleteOverrideResponseBody$Outbound
    | undefined;
};

/** @internal */
export const RatelimitDeleteOverrideResponse$outboundSchema: z.ZodType<
  RatelimitDeleteOverrideResponse$Outbound,
  z.ZodTypeDef,
  RatelimitDeleteOverrideResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  v2RatelimitDeleteOverrideResponseBody: components
    .V2RatelimitDeleteOverrideResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    v2RatelimitDeleteOverrideResponseBody:
      "V2RatelimitDeleteOverrideResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RatelimitDeleteOverrideResponse$ {
  /** @deprecated use `RatelimitDeleteOverrideResponse$inboundSchema` instead. */
  export const inboundSchema = RatelimitDeleteOverrideResponse$inboundSchema;
  /** @deprecated use `RatelimitDeleteOverrideResponse$outboundSchema` instead. */
  export const outboundSchema = RatelimitDeleteOverrideResponse$outboundSchema;
  /** @deprecated use `RatelimitDeleteOverrideResponse$Outbound` instead. */
  export type Outbound = RatelimitDeleteOverrideResponse$Outbound;
}

export function ratelimitDeleteOverrideResponseToJSON(
  ratelimitDeleteOverrideResponse: RatelimitDeleteOverrideResponse,
): string {
  return JSON.stringify(
    RatelimitDeleteOverrideResponse$outboundSchema.parse(
      ratelimitDeleteOverrideResponse,
    ),
  );
}

export function ratelimitDeleteOverrideResponseFromJSON(
  jsonString: string,
): SafeParseResult<RatelimitDeleteOverrideResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RatelimitDeleteOverrideResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RatelimitDeleteOverrideResponse' from JSON`,
  );
}
