/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RatelimitGetOverrideResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  v2RatelimitGetOverrideResponseBody?:
    | components.V2RatelimitGetOverrideResponseBody
    | undefined;
};

/** @internal */
export const RatelimitGetOverrideResponse$inboundSchema: z.ZodType<
  RatelimitGetOverrideResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  V2RatelimitGetOverrideResponseBody: components
    .V2RatelimitGetOverrideResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "V2RatelimitGetOverrideResponseBody": "v2RatelimitGetOverrideResponseBody",
  });
});

/** @internal */
export type RatelimitGetOverrideResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  V2RatelimitGetOverrideResponseBody?:
    | components.V2RatelimitGetOverrideResponseBody$Outbound
    | undefined;
};

/** @internal */
export const RatelimitGetOverrideResponse$outboundSchema: z.ZodType<
  RatelimitGetOverrideResponse$Outbound,
  z.ZodTypeDef,
  RatelimitGetOverrideResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  v2RatelimitGetOverrideResponseBody: components
    .V2RatelimitGetOverrideResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    v2RatelimitGetOverrideResponseBody: "V2RatelimitGetOverrideResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RatelimitGetOverrideResponse$ {
  /** @deprecated use `RatelimitGetOverrideResponse$inboundSchema` instead. */
  export const inboundSchema = RatelimitGetOverrideResponse$inboundSchema;
  /** @deprecated use `RatelimitGetOverrideResponse$outboundSchema` instead. */
  export const outboundSchema = RatelimitGetOverrideResponse$outboundSchema;
  /** @deprecated use `RatelimitGetOverrideResponse$Outbound` instead. */
  export type Outbound = RatelimitGetOverrideResponse$Outbound;
}

export function ratelimitGetOverrideResponseToJSON(
  ratelimitGetOverrideResponse: RatelimitGetOverrideResponse,
): string {
  return JSON.stringify(
    RatelimitGetOverrideResponse$outboundSchema.parse(
      ratelimitGetOverrideResponse,
    ),
  );
}

export function ratelimitGetOverrideResponseFromJSON(
  jsonString: string,
): SafeParseResult<RatelimitGetOverrideResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RatelimitGetOverrideResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RatelimitGetOverrideResponse' from JSON`,
  );
}
