/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1RatelimitLimitResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  v2RatelimitLimitResponseBody?:
    | components.V2RatelimitLimitResponseBody
    | undefined;
};

/** @internal */
export const V1RatelimitLimitResponse$inboundSchema: z.ZodType<
  V1RatelimitLimitResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  V2RatelimitLimitResponseBody: components
    .V2RatelimitLimitResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "V2RatelimitLimitResponseBody": "v2RatelimitLimitResponseBody",
  });
});

/** @internal */
export type V1RatelimitLimitResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  V2RatelimitLimitResponseBody?:
    | components.V2RatelimitLimitResponseBody$Outbound
    | undefined;
};

/** @internal */
export const V1RatelimitLimitResponse$outboundSchema: z.ZodType<
  V1RatelimitLimitResponse$Outbound,
  z.ZodTypeDef,
  V1RatelimitLimitResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  v2RatelimitLimitResponseBody: components
    .V2RatelimitLimitResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    v2RatelimitLimitResponseBody: "V2RatelimitLimitResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1RatelimitLimitResponse$ {
  /** @deprecated use `V1RatelimitLimitResponse$inboundSchema` instead. */
  export const inboundSchema = V1RatelimitLimitResponse$inboundSchema;
  /** @deprecated use `V1RatelimitLimitResponse$outboundSchema` instead. */
  export const outboundSchema = V1RatelimitLimitResponse$outboundSchema;
  /** @deprecated use `V1RatelimitLimitResponse$Outbound` instead. */
  export type Outbound = V1RatelimitLimitResponse$Outbound;
}

export function v1RatelimitLimitResponseToJSON(
  v1RatelimitLimitResponse: V1RatelimitLimitResponse,
): string {
  return JSON.stringify(
    V1RatelimitLimitResponse$outboundSchema.parse(v1RatelimitLimitResponse),
  );
}

export function v1RatelimitLimitResponseFromJSON(
  jsonString: string,
): SafeParseResult<V1RatelimitLimitResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1RatelimitLimitResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1RatelimitLimitResponse' from JSON`,
  );
}
