/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RatelimitGetOverrideResponseData = {
  /**
   * The id of the namespace.
   */
  namespaceId: string;
  /**
   * The id of the override.
   */
  overrideId: string;
  /**
   * The duration in milliseconds for the rate limit window.
   */
  duration: number;
  /**
   * Identifier of your user, this can be their userId, an email, an ip or anything else. Wildcards ( * ) can be used to match multiple identifiers, More info can be found at https://www.unkey.com/docs/ratelimiting/overrides#wildcard-rules
   */
  identifier: string;
  /**
   * The maximum number of requests allowed.
   */
  limit: number;
};

/** @internal */
export const RatelimitGetOverrideResponseData$inboundSchema: z.ZodType<
  RatelimitGetOverrideResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespaceId: z.string(),
  overrideId: z.string(),
  duration: z.number().int(),
  identifier: z.string(),
  limit: z.number().int(),
});

/** @internal */
export type RatelimitGetOverrideResponseData$Outbound = {
  namespaceId: string;
  overrideId: string;
  duration: number;
  identifier: string;
  limit: number;
};

/** @internal */
export const RatelimitGetOverrideResponseData$outboundSchema: z.ZodType<
  RatelimitGetOverrideResponseData$Outbound,
  z.ZodTypeDef,
  RatelimitGetOverrideResponseData
> = z.object({
  namespaceId: z.string(),
  overrideId: z.string(),
  duration: z.number().int(),
  identifier: z.string(),
  limit: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RatelimitGetOverrideResponseData$ {
  /** @deprecated use `RatelimitGetOverrideResponseData$inboundSchema` instead. */
  export const inboundSchema = RatelimitGetOverrideResponseData$inboundSchema;
  /** @deprecated use `RatelimitGetOverrideResponseData$outboundSchema` instead. */
  export const outboundSchema = RatelimitGetOverrideResponseData$outboundSchema;
  /** @deprecated use `RatelimitGetOverrideResponseData$Outbound` instead. */
  export type Outbound = RatelimitGetOverrideResponseData$Outbound;
}

export function ratelimitGetOverrideResponseDataToJSON(
  ratelimitGetOverrideResponseData: RatelimitGetOverrideResponseData,
): string {
  return JSON.stringify(
    RatelimitGetOverrideResponseData$outboundSchema.parse(
      ratelimitGetOverrideResponseData,
    ),
  );
}

export function ratelimitGetOverrideResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<RatelimitGetOverrideResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RatelimitGetOverrideResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RatelimitGetOverrideResponseData' from JSON`,
  );
}
