/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Ratelimit = {
  /**
   * The name of this limit. You will need to use this again when verifying a key.
   */
  name: string;
  /**
   * How many requests may pass within a given window before requests are rejected.
   */
  limit: number;
  /**
   * The duration for each ratelimit window in milliseconds.
   */
  duration: number;
};

/** @internal */
export const Ratelimit$inboundSchema: z.ZodType<
  Ratelimit,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  limit: z.number().int(),
  duration: z.number().int(),
});

/** @internal */
export type Ratelimit$Outbound = {
  name: string;
  limit: number;
  duration: number;
};

/** @internal */
export const Ratelimit$outboundSchema: z.ZodType<
  Ratelimit$Outbound,
  z.ZodTypeDef,
  Ratelimit
> = z.object({
  name: z.string(),
  limit: z.number().int(),
  duration: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ratelimit$ {
  /** @deprecated use `Ratelimit$inboundSchema` instead. */
  export const inboundSchema = Ratelimit$inboundSchema;
  /** @deprecated use `Ratelimit$outboundSchema` instead. */
  export const outboundSchema = Ratelimit$outboundSchema;
  /** @deprecated use `Ratelimit$Outbound` instead. */
  export type Outbound = Ratelimit$Outbound;
}

export function ratelimitToJSON(ratelimit: Ratelimit): string {
  return JSON.stringify(Ratelimit$outboundSchema.parse(ratelimit));
}

export function ratelimitFromJSON(
  jsonString: string,
): SafeParseResult<Ratelimit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ratelimit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ratelimit' from JSON`,
  );
}
