/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Two = {
  /**
   * The id of this identity in your system.
   *
   * @remarks
   *
   * This usually comes from your authentication provider and could be a userId, organisationId or even an email.
   * It does not matter what you use, as long as it uniquely identifies something in your application.
   */
  externalId?: string | undefined;
  /**
   * The Unkey Identity ID.
   */
  identityId: string;
};

export type One = {
  /**
   * The id of this identity in your system.
   *
   * @remarks
   *
   * This usually comes from your authentication provider and could be a userId, organisationId or even an email.
   * It does not matter what you use, as long as it uniquely identifies something in your application.
   */
  externalId: string;
  /**
   * The Unkey Identity ID.
   */
  identityId?: string | undefined;
};

export type V2IdentitiesDeleteIdentityRequestBody = One | Two;

/** @internal */
export const Two$inboundSchema: z.ZodType<Two, z.ZodTypeDef, unknown> = z
  .object({
    externalId: z.string().optional(),
    identityId: z.string(),
  });

/** @internal */
export type Two$Outbound = {
  externalId?: string | undefined;
  identityId: string;
};

/** @internal */
export const Two$outboundSchema: z.ZodType<Two$Outbound, z.ZodTypeDef, Two> = z
  .object({
    externalId: z.string().optional(),
    identityId: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Two$ {
  /** @deprecated use `Two$inboundSchema` instead. */
  export const inboundSchema = Two$inboundSchema;
  /** @deprecated use `Two$outboundSchema` instead. */
  export const outboundSchema = Two$outboundSchema;
  /** @deprecated use `Two$Outbound` instead. */
  export type Outbound = Two$Outbound;
}

export function twoToJSON(two: Two): string {
  return JSON.stringify(Two$outboundSchema.parse(two));
}

export function twoFromJSON(
  jsonString: string,
): SafeParseResult<Two, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Two$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Two' from JSON`,
  );
}

/** @internal */
export const One$inboundSchema: z.ZodType<One, z.ZodTypeDef, unknown> = z
  .object({
    externalId: z.string(),
    identityId: z.string().optional(),
  });

/** @internal */
export type One$Outbound = {
  externalId: string;
  identityId?: string | undefined;
};

/** @internal */
export const One$outboundSchema: z.ZodType<One$Outbound, z.ZodTypeDef, One> = z
  .object({
    externalId: z.string(),
    identityId: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace One$ {
  /** @deprecated use `One$inboundSchema` instead. */
  export const inboundSchema = One$inboundSchema;
  /** @deprecated use `One$outboundSchema` instead. */
  export const outboundSchema = One$outboundSchema;
  /** @deprecated use `One$Outbound` instead. */
  export type Outbound = One$Outbound;
}

export function oneToJSON(one: One): string {
  return JSON.stringify(One$outboundSchema.parse(one));
}

export function oneFromJSON(
  jsonString: string,
): SafeParseResult<One, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => One$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'One' from JSON`,
  );
}

/** @internal */
export const V2IdentitiesDeleteIdentityRequestBody$inboundSchema: z.ZodType<
  V2IdentitiesDeleteIdentityRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([z.lazy(() => One$inboundSchema), z.lazy(() => Two$inboundSchema)]);

/** @internal */
export type V2IdentitiesDeleteIdentityRequestBody$Outbound =
  | One$Outbound
  | Two$Outbound;

/** @internal */
export const V2IdentitiesDeleteIdentityRequestBody$outboundSchema: z.ZodType<
  V2IdentitiesDeleteIdentityRequestBody$Outbound,
  z.ZodTypeDef,
  V2IdentitiesDeleteIdentityRequestBody
> = z.union([
  z.lazy(() => One$outboundSchema),
  z.lazy(() => Two$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2IdentitiesDeleteIdentityRequestBody$ {
  /** @deprecated use `V2IdentitiesDeleteIdentityRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    V2IdentitiesDeleteIdentityRequestBody$inboundSchema;
  /** @deprecated use `V2IdentitiesDeleteIdentityRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    V2IdentitiesDeleteIdentityRequestBody$outboundSchema;
  /** @deprecated use `V2IdentitiesDeleteIdentityRequestBody$Outbound` instead. */
  export type Outbound = V2IdentitiesDeleteIdentityRequestBody$Outbound;
}

export function v2IdentitiesDeleteIdentityRequestBodyToJSON(
  v2IdentitiesDeleteIdentityRequestBody: V2IdentitiesDeleteIdentityRequestBody,
): string {
  return JSON.stringify(
    V2IdentitiesDeleteIdentityRequestBody$outboundSchema.parse(
      v2IdentitiesDeleteIdentityRequestBody,
    ),
  );
}

export function v2IdentitiesDeleteIdentityRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2IdentitiesDeleteIdentityRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V2IdentitiesDeleteIdentityRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2IdentitiesDeleteIdentityRequestBody' from JSON`,
  );
}
