/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2IdentitiesDeleteIdentityResponseBody = {};

/** @internal */
export const V2IdentitiesDeleteIdentityResponseBody$inboundSchema: z.ZodType<
  V2IdentitiesDeleteIdentityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type V2IdentitiesDeleteIdentityResponseBody$Outbound = {};

/** @internal */
export const V2IdentitiesDeleteIdentityResponseBody$outboundSchema: z.ZodType<
  V2IdentitiesDeleteIdentityResponseBody$Outbound,
  z.ZodTypeDef,
  V2IdentitiesDeleteIdentityResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2IdentitiesDeleteIdentityResponseBody$ {
  /** @deprecated use `V2IdentitiesDeleteIdentityResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    V2IdentitiesDeleteIdentityResponseBody$inboundSchema;
  /** @deprecated use `V2IdentitiesDeleteIdentityResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    V2IdentitiesDeleteIdentityResponseBody$outboundSchema;
  /** @deprecated use `V2IdentitiesDeleteIdentityResponseBody$Outbound` instead. */
  export type Outbound = V2IdentitiesDeleteIdentityResponseBody$Outbound;
}

export function v2IdentitiesDeleteIdentityResponseBodyToJSON(
  v2IdentitiesDeleteIdentityResponseBody:
    V2IdentitiesDeleteIdentityResponseBody,
): string {
  return JSON.stringify(
    V2IdentitiesDeleteIdentityResponseBody$outboundSchema.parse(
      v2IdentitiesDeleteIdentityResponseBody,
    ),
  );
}

export function v2IdentitiesDeleteIdentityResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2IdentitiesDeleteIdentityResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V2IdentitiesDeleteIdentityResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2IdentitiesDeleteIdentityResponseBody' from JSON`,
  );
}
