/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2RatelimitLimitResponseBody = {
  /**
   * The maximum number of requests allowed.
   */
  limit: number;
  /**
   * The number of requests remaining in the current window.
   */
  remaining: number;
  /**
   * The time in milliseconds when the rate limit will reset.
   */
  reset: number;
  /**
   * Whether the request passed the ratelimit. If false, the request must be blocked.
   */
  success: boolean;
  /**
   * The override that was used. May be empty
   */
  overrideId?: string | undefined;
};

/** @internal */
export const V2RatelimitLimitResponseBody$inboundSchema: z.ZodType<
  V2RatelimitLimitResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  remaining: z.number().int(),
  reset: z.number().int(),
  success: z.boolean(),
  overrideId: z.string().optional(),
});

/** @internal */
export type V2RatelimitLimitResponseBody$Outbound = {
  limit: number;
  remaining: number;
  reset: number;
  success: boolean;
  overrideId?: string | undefined;
};

/** @internal */
export const V2RatelimitLimitResponseBody$outboundSchema: z.ZodType<
  V2RatelimitLimitResponseBody$Outbound,
  z.ZodTypeDef,
  V2RatelimitLimitResponseBody
> = z.object({
  limit: z.number().int(),
  remaining: z.number().int(),
  reset: z.number().int(),
  success: z.boolean(),
  overrideId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2RatelimitLimitResponseBody$ {
  /** @deprecated use `V2RatelimitLimitResponseBody$inboundSchema` instead. */
  export const inboundSchema = V2RatelimitLimitResponseBody$inboundSchema;
  /** @deprecated use `V2RatelimitLimitResponseBody$outboundSchema` instead. */
  export const outboundSchema = V2RatelimitLimitResponseBody$outboundSchema;
  /** @deprecated use `V2RatelimitLimitResponseBody$Outbound` instead. */
  export type Outbound = V2RatelimitLimitResponseBody$Outbound;
}

export function v2RatelimitLimitResponseBodyToJSON(
  v2RatelimitLimitResponseBody: V2RatelimitLimitResponseBody,
): string {
  return JSON.stringify(
    V2RatelimitLimitResponseBody$outboundSchema.parse(
      v2RatelimitLimitResponseBody,
    ),
  );
}

export function v2RatelimitLimitResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2RatelimitLimitResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2RatelimitLimitResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2RatelimitLimitResponseBody' from JSON`,
  );
}
